# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-20.04"
  config.vm.box_check_update = true
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "192.168.50.20"
  config.vm.network "private_network", ip: "192.168.50.254"
  config.vm.synced_folder "./proyectos", "/var/www/html", 
    create: true
  
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  
end
 
config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y apache2 libapache2-mod-php php-mysql mariadb-server
   SHELL
end



